# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/robert/Projects/C++/RoboCore

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/robert/Projects/C++/RoboCore

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/robert/Projects/C++/RoboCore/CMakeFiles /home/robert/Projects/C++/RoboCore//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/robert/Projects/C++/RoboCore/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RoboCore

# Build rule for target.
RoboCore: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RoboCore
.PHONY : RoboCore

# fast build rule for target.
RoboCore/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoboCore.dir/build.make CMakeFiles/RoboCore.dir/build
.PHONY : RoboCore/fast

src/Display.o: src/Display.cpp.o
.PHONY : src/Display.o

# target to build an object file
src/Display.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoboCore.dir/build.make CMakeFiles/RoboCore.dir/src/Display.cpp.o
.PHONY : src/Display.cpp.o

src/Display.i: src/Display.cpp.i
.PHONY : src/Display.i

# target to preprocess a source file
src/Display.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoboCore.dir/build.make CMakeFiles/RoboCore.dir/src/Display.cpp.i
.PHONY : src/Display.cpp.i

src/Display.s: src/Display.cpp.s
.PHONY : src/Display.s

# target to generate assembly for a file
src/Display.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoboCore.dir/build.make CMakeFiles/RoboCore.dir/src/Display.cpp.s
.PHONY : src/Display.cpp.s

src/File.o: src/File.cpp.o
.PHONY : src/File.o

# target to build an object file
src/File.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoboCore.dir/build.make CMakeFiles/RoboCore.dir/src/File.cpp.o
.PHONY : src/File.cpp.o

src/File.i: src/File.cpp.i
.PHONY : src/File.i

# target to preprocess a source file
src/File.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoboCore.dir/build.make CMakeFiles/RoboCore.dir/src/File.cpp.i
.PHONY : src/File.cpp.i

src/File.s: src/File.cpp.s
.PHONY : src/File.s

# target to generate assembly for a file
src/File.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoboCore.dir/build.make CMakeFiles/RoboCore.dir/src/File.cpp.s
.PHONY : src/File.cpp.s

src/Filter.o: src/Filter.cpp.o
.PHONY : src/Filter.o

# target to build an object file
src/Filter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoboCore.dir/build.make CMakeFiles/RoboCore.dir/src/Filter.cpp.o
.PHONY : src/Filter.cpp.o

src/Filter.i: src/Filter.cpp.i
.PHONY : src/Filter.i

# target to preprocess a source file
src/Filter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoboCore.dir/build.make CMakeFiles/RoboCore.dir/src/Filter.cpp.i
.PHONY : src/Filter.cpp.i

src/Filter.s: src/Filter.cpp.s
.PHONY : src/Filter.s

# target to generate assembly for a file
src/Filter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoboCore.dir/build.make CMakeFiles/RoboCore.dir/src/Filter.cpp.s
.PHONY : src/Filter.cpp.s

src/Keyboard.o: src/Keyboard.cpp.o
.PHONY : src/Keyboard.o

# target to build an object file
src/Keyboard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoboCore.dir/build.make CMakeFiles/RoboCore.dir/src/Keyboard.cpp.o
.PHONY : src/Keyboard.cpp.o

src/Keyboard.i: src/Keyboard.cpp.i
.PHONY : src/Keyboard.i

# target to preprocess a source file
src/Keyboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoboCore.dir/build.make CMakeFiles/RoboCore.dir/src/Keyboard.cpp.i
.PHONY : src/Keyboard.cpp.i

src/Keyboard.s: src/Keyboard.cpp.s
.PHONY : src/Keyboard.s

# target to generate assembly for a file
src/Keyboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoboCore.dir/build.make CMakeFiles/RoboCore.dir/src/Keyboard.cpp.s
.PHONY : src/Keyboard.cpp.s

src/Main.o: src/Main.cpp.o
.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoboCore.dir/build.make CMakeFiles/RoboCore.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i
.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoboCore.dir/build.make CMakeFiles/RoboCore.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s
.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoboCore.dir/build.make CMakeFiles/RoboCore.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/OCVCamera.o: src/OCVCamera.cpp.o
.PHONY : src/OCVCamera.o

# target to build an object file
src/OCVCamera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoboCore.dir/build.make CMakeFiles/RoboCore.dir/src/OCVCamera.cpp.o
.PHONY : src/OCVCamera.cpp.o

src/OCVCamera.i: src/OCVCamera.cpp.i
.PHONY : src/OCVCamera.i

# target to preprocess a source file
src/OCVCamera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoboCore.dir/build.make CMakeFiles/RoboCore.dir/src/OCVCamera.cpp.i
.PHONY : src/OCVCamera.cpp.i

src/OCVCamera.s: src/OCVCamera.cpp.s
.PHONY : src/OCVCamera.s

# target to generate assembly for a file
src/OCVCamera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoboCore.dir/build.make CMakeFiles/RoboCore.dir/src/OCVCamera.cpp.s
.PHONY : src/OCVCamera.cpp.s

src/UARTController.o: src/UARTController.cpp.o
.PHONY : src/UARTController.o

# target to build an object file
src/UARTController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoboCore.dir/build.make CMakeFiles/RoboCore.dir/src/UARTController.cpp.o
.PHONY : src/UARTController.cpp.o

src/UARTController.i: src/UARTController.cpp.i
.PHONY : src/UARTController.i

# target to preprocess a source file
src/UARTController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoboCore.dir/build.make CMakeFiles/RoboCore.dir/src/UARTController.cpp.i
.PHONY : src/UARTController.cpp.i

src/UARTController.s: src/UARTController.cpp.s
.PHONY : src/UARTController.s

# target to generate assembly for a file
src/UARTController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoboCore.dir/build.make CMakeFiles/RoboCore.dir/src/UARTController.cpp.s
.PHONY : src/UARTController.cpp.s

src/ZEDCamera.o: src/ZEDCamera.cpp.o
.PHONY : src/ZEDCamera.o

# target to build an object file
src/ZEDCamera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoboCore.dir/build.make CMakeFiles/RoboCore.dir/src/ZEDCamera.cpp.o
.PHONY : src/ZEDCamera.cpp.o

src/ZEDCamera.i: src/ZEDCamera.cpp.i
.PHONY : src/ZEDCamera.i

# target to preprocess a source file
src/ZEDCamera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoboCore.dir/build.make CMakeFiles/RoboCore.dir/src/ZEDCamera.cpp.i
.PHONY : src/ZEDCamera.cpp.i

src/ZEDCamera.s: src/ZEDCamera.cpp.s
.PHONY : src/ZEDCamera.s

# target to generate assembly for a file
src/ZEDCamera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RoboCore.dir/build.make CMakeFiles/RoboCore.dir/src/ZEDCamera.cpp.s
.PHONY : src/ZEDCamera.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... RoboCore"
	@echo "... src/Display.o"
	@echo "... src/Display.i"
	@echo "... src/Display.s"
	@echo "... src/File.o"
	@echo "... src/File.i"
	@echo "... src/File.s"
	@echo "... src/Filter.o"
	@echo "... src/Filter.i"
	@echo "... src/Filter.s"
	@echo "... src/Keyboard.o"
	@echo "... src/Keyboard.i"
	@echo "... src/Keyboard.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/OCVCamera.o"
	@echo "... src/OCVCamera.i"
	@echo "... src/OCVCamera.s"
	@echo "... src/UARTController.o"
	@echo "... src/UARTController.i"
	@echo "... src/UARTController.s"
	@echo "... src/ZEDCamera.o"
	@echo "... src/ZEDCamera.i"
	@echo "... src/ZEDCamera.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

